
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Amir Mohammad  ## put your name
title: 'Computer Engineer'  ## your title
location: TEHRAN, IRAN


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url



# Update all the sections by editing the files inside _includes folder.
